import initalTabNavAnimais from './modules/tab-nav.js';
import arccordion from './modules/arccordion.js';
import animeScroll from './modules/anime-scroll.js';
import scrollSuave from './modules/scroll-suave.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropDownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/funcionamento.js';

initalTabNavAnimais();
arccordion();
animeScroll();
scrollSuave();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();